### ISSUE TITLE
unable to install and execute ELK with virtual box 5.0.20 and vagrant 1.8.5

### ISSUE THREAD

**Issue by Divyakoganti** [bhaskarvk/vagrant-elk-cluster#10]
Not able to install the plugins of elastic search with virtual box 5.0.20 version. it showing errors like

NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify) ..........
and so on .

i am using vagrant 1.8.5 and virtual box 5.0.20 ,next started installing as per the instructions but not able to install properly and when i opened kibana page it shows unable to fetch index and in logs/logstash-vm251.log file it shows could not find plugin for elastic search.

can you please help me with the solution.

**Comment by bhaskarvk** [comment]
I haven't touched this in over an year. I'll look at it over the week end.

**Comment by bhaskarvk** [comment]
@Divyakoganti I just pushed some new changes, can you retry.

**Comment by Divyakoganti** [comment]
ok thank you very much  for the reply .i will check and get back to you.

**Comment by Divyakoganti** [comment]
How can we install without lib folder ? installation procedure is in lib folder .

**Comment by Divyakoganti** [comment]
not able to install with the new changes could you please help in the steps for installation process.
like i  am using centos6.5 is it any problem?
and vm box i am using is  vagrant box add hdptest_vm https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box

or should i use centos 7 only for this process, if  so can you  send the link for centos7 

please help me with the solution for proper installation of this vagant-elk-cluster.

**Comment by bhaskarvk** [comment]
give me your host details , did you make any changes to the vagrant file or any other file in the repo? Lastly please submit the entire output.

**Comment by Divyakoganti** [comment]
[upgrade-es.docx](https://github.com/bhaskarvk/vagrant-elk-cluster/files/547305/upgrade-es.docx)
[upgrade-kibana.docx](https://github.com/bhaskarvk/vagrant-elk-cluster/files/547304/upgrade-kibana.docx)
[upgrade-logstash.docx](https://github.com/bhaskarvk/vagrant-elk-cluster/files/547303/upgrade-logstash.docx)
[Vagrantfile.docx](https://github.com/bhaskarvk/vagrant-elk-cluster/files/547302/Vagrantfile.docx)

These are the files I modified,because i am using centos 6.5   but remaining are same.
i kept same CONF folder,same LIB folder with  upgrade-es.sh, upgrade-kibana.sh, upgrade-logstash.sh modifications,same SCRIPT folder and some modification on vagrant file.

The output is like when i say vagrant up not able to install it is showing there was error 

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "11b3c4cb-656b-49bf-84c9-4d920cb47a07", "--type", "headless"]

Stderr: VBoxManage.exe: error: The virtual machine 'elasticsearch-vm1' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\HalonW\VirtualBox VMs\elasticsearch-vm1\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

**Comment by bhaskarvk** [comment]
I don't have Microsoft Office. I think you are making this way more complex than it needs be. Here's what I want you to do in order for me to help to resolve this issue.

a) Try my code w/o any modification and see if that works and let me know.
b) Fork my repo and make your changes and commit them, that way I can check your cod properly w/o needing access to microsoft office.
c) When you start up vagrant at the root of this repo, there's a director created called 'logs' , upload each file in that directory to gist.github.com, or attach them to this issue.

**Comment by Divyakoganti** [comment]
ok thankyou very much  for the reply .i will try and get back to you.

**Comment by Divyakoganti** [comment]
can you please suggest  best version for vagrant and virtual box and in vagrant file what should i include under 
 **config.vm.box**
So that  i may not have any issues during executions.
