### ISSUE TITLE
Doesn't work under virtualbox

### ISSUE THREAD

**Issue by bhaskarvk** [bhaskarvk/vagrant-elk-cluster#3]
Doesn't work under Virtualbox

**Comment by Divyakoganti** [comment]
Not able to install the plugins of elastic search  with virtual box 5.0.20 version. it showing errors like

NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify) ..........
and so on .

can you please suggest the solution and  any compatible version for your project.

**Comment by Divyakoganti** [comment]
i am using vagrant 1.8.5 and virtual box 5.0.20 ,next started installing as per the instructions but not able to install properly and when i opened kibana page it shows unable to fetch index and in logs/logstash-vm251.log file it shows could not find plugin for elastic search.

can you please help me with the solution.
