### ISSUE TITLE
Script fails on vm1

### ISSUE THREAD

**Issue by ropollock** [bhaskarvk/vagrant-elk-cluster#9]
I've read the instructions several times and I've matched all the versions listed but when I run vagrant up command I get this error.

==> vm1: /tmp/vagrant-shell: /vagrant/scripts/node-start: /bin/bash^M: bad interpreter: No such file or directory

Only one vm gets created as a result. What am I doing wrong?

**Comment by bhaskarvk** [comment]
What's your host OS ?

**Comment by ropollock** [comment]
The host is Windows 10.

**Comment by bhaskarvk** [comment]
CLosing as this is a Unix only solution. You may have luch with CYgwin+bash though.

**Comment by bhaskarvk** [comment]
CLosing as this is a Unix only solution. You may have luch with CYgwin+bash though.

**Comment by bhaskarvk** [comment]
CLosing as this is a Unix only solution. You may have luch with CYgwin+bash though.

**Comment by bhaskarvk** [comment]
CLosing as this is a Unix only solution. You may have luch with CYgwin+bash though.

**Comment by bhaskarvk** [comment]
CLosing as this is a Unix only solution. You may have luch with CYgwin+bash though.
